# -------------------------------------------------------------------------------------------- #
# ---------------------------------- Parts parameters ---------------------------------------- #
# -------------------------------------------------------------------------------------------- #
PLC_TOKEN = {
    "token" : 0,
}


PLC_DEFAULT_VARIABLES_INT ={
    ".step_auto" : 0,
    ".step_semi" : 0,

}


# -------------------------------------------------------------------------------------------- #
# --------------------------- LOCAL VARIABLES SESOR VALUES ----------------------------------- #
# -------------------------------------------------------------------------------------------- #


PLC_DEFAULT_VARIABLES = {
    # //Okuma 1
    'CH1_I_M181':False,
    'CH1_I_M182':False,
    'CH1_I_M183':False,
    'CH1_I_M184':False,
    'CH1_I_AL':False,
    'CH1_I_PSA':False,
    'CH1_I_NPA':False,
    'CH1_I_NPR':False,
    'CH1_I_NCR':False,
    #Okuma 2
    'CH2_I_M181':False,
    'CH2_I_M182':False,
    'CH2_I_M183':False,
    'CH2_I_M184':False,
    'CH2_I_AL':False,
    'CH2_I_PSA':False,
    'CH2_I_NPA':False,
    'CH2_I_NPR':False,
    'CH2_I_NCR':False,
    #Okuma 3
    'CH3_I_M181':False,
    'CH3_I_M182':False,
    'CH3_I_M183':False,
    'CH3_I_M184':False,
    'CH3_I_AL':False,
    'CH3_I_PSA':False,
    'CH3_I_NPA':False,
    'CH3_I_NPR':False,
    'CH3_I_NCR':False,
    #Okuma 4
    'CH4_I_M181':False,
    'CH4_I_M182':False,
    'CH4_I_M183':False,
    'CH4_I_M184':False,
    'CH4_I_AL':False,
    'CH4_I_PSA':False,
    'CH4_I_NPA':False,
    'CH4_I_NPR':False,
    'CH4_I_NCR':False,
    #Robot
    'R_I_AL':False,
    'R_I_HF':False,
    'R_I_ID':False,
    'R_I_AUT_SEM':False,
    'R_O_AUT_SEM':False,
    'R_I_30_40':False,
    'R_I_CAS':False,
    'R_I_BIT0_CH':False,
    'R_I_BIT1_CH':False,
    'R_I_PAL':False,
    'R_I_DRW':False,
    'R_I_MA':False,
    'R_I_GET_PUT':False,
    'R_I_MA_CH':False,
    'R_I_G1_PS':False,
    'R_I_G2_PS':False,
    'R_I_FLS':False,
    'R_I_RLS':False,
    #Mesa 1
    'MA1_I_DR_U_PS_1':False,
    'MA1_I_DR_U_PS_2':False,
    'MA1_I_DR_D_PS_1':False,
    'MA1_I_DR_D_PS_2':False,
    'MA1_I_GS_UP':False,
    'MA1_I_GS_DN':False,
    'MA1_I_DR_U_ES_1':False,
    'MA1_I_DR_U_ES_2':False,
    'MA1_I_DR_D_ES_1':False,
    'MA1_I_DR_D_ES_2':False,
    'MA1_I_DR_U_NS':False,
    'MA1_I_DR_D_NS':False,
    'MA1_I_DR_U_BP_1_SA':False,
    'MA1_I_DR_U_BP_1_SR':False,
    'MA1_I_DR_U_BP_2_SA':False,
    'MA1_I_DR_U_BP_2_SR':False,
    'MA1_I_DR_D_BP_1_SA':False,
    'MA1_I_DR_D_BP_1_SR':False,
    'MA1_I_DR_D_BP_2_SA':False,
    'MA1_I_DR_D_BP_2_SR':False,
    'MA1_I_EMS':False,
    'MA1_I_SE_UP':False,
    'MA1_I_SE_DN':False,
    #Mesa 2
    'MA2_I_DR_U_PS_1':False,
    'MA2_I_DR_U_PS_2':False,
    'MA2_I_DR_D_PS_1':False,
    'MA2_I_DR_D_PS_2':False,
    'MA2_I_GS_UP':False,
    'MA2_I_GS_DN':False,
    'MA2_I_DR_U_ES_1':False,
    'MA2_I_DR_U_ES_2':False,
    'MA2_I_DR_D_ES_1':False,
    'MA2_I_DR_D_ES_2':False,
    'MA2_I_DR_U_NS':False,
    'MA2_I_DR_D_NS':False,
    'MA2_I_DR_U_BP_1_SA':False,
    'MA2_I_DR_U_BP_1_SR':False,
    'MA2_I_DR_U_BP_2_SA':False,
    'MA2_I_DR_U_BP_2_SR':False,
    'MA2_I_DR_D_BP_1_SA':False,
    'MA2_I_DR_D_BP_1_SR':False,
    'MA2_I_DR_D_BP_2_SA':False,
    'MA2_I_DR_D_BP_2_SR':False,
    'MA2_I_EMS':False,
    'MA2_I_SE_UP':False,
    'MA2_I_SE_DN':False,
    #Gral
    'Emergency':False,
    'Robot_IDLE':False,
    #Errores
    '.emergency_active':False,
    '.ma1_drd_endstops':False,
    '.ma1_dru_endstops':False,
    '.ma1_gs_dn':False,
    '.ma1_gs_up':False,
    '.ma1_nsense':False,
    '.ma2_drd_endstops':False,
    '.ma2_dru_endstops':False,
    '.ma2_gs_dn':False,
    '.ma2_gs_up':False,
    '.ma2_nsense':False,
    '.r_manualmode':False,
    '.r_program':False,
    '.r_gp1_not_free':False,
    '.r_gp2_not_free':False,
    '.r_gp1_free':False,
    '.r_gp2_free':False,
    '.r_not_idle':False,
    '.r_not_home':False,
    '.r_alarm':False,
    '.r_flimit':False,
    '.r_rlimit':False,
    '.ch1_nsense_ret':False,
    '.ch1_nsense_adv':False,
    '.ch1_alarm':False,
    '.ch1_psa':False,
    '.ch2_nsense_ret':False,
    '.ch2_nsense_adv':False,
    '.ch2_alarm':False,
    '.ch2_psa':False,
    '.ch3_nsense_ret':False,
    '.ch3_nsense_adv':False,
    '.ch3_alarm':False,
    '.ch3_psa':False,
    '.ch4_nsense_ret':False,
    '.ch4_nsense_adv':False,
    '.ch4_alarm':False,
    '.ch4_psa':False,
    '.init_error':False,
    '.max_unblock_error':False,
    '.max_block_error':False,
    '.max_pallet_present':False,
    '.max_dr_position':False,
    '.max_gs_up':False,
    '.chx_robot_not_allowed':False,
    '.chx_pressure_error':False,
    '.chx_nsense_adv':False,
    '.chx_nsense_ret':False,
    '.chx_alarm':False,
    '.chx_not_available':False,
    #Tags
    '.pause_auto':False,
    '.last_auto':False,
    '.pause_semi':False,
    '.CH1_DISABLE':False,
    '.CH2_DISABLE':False,
    '.CH3_DISABLE':False,
    '.CH4_DISABLE':False,
    '.MA1_DISABLE':False,
    '.MA2_DISABLE':False,
}


# -------------------------------------------------------------------------------------------- #
# ------------------------------ PLC DIRECCIONAMIENTOS --------------------------------------- #
# -------------------------------------------------------------------------------------------- #


LIST_OF_DIRECTIONS = [
# //Okuma 1
    'CH1_I_M181',
    'CH1_I_M182',
    'CH1_I_M183',
    'CH1_I_M184',
    'CH1_I_AL',
    'CH1_I_PSA',
    'CH1_I_NPA',
    'CH1_I_NPR',
    'CH1_I_NCR',
# //Okuma 2
    'CH2_I_M181',
    'CH2_I_M182',
    'CH2_I_M183',
    'CH2_I_M184',
    'CH2_I_AL',
    'CH2_I_PSA',
    'CH2_I_NPA',
    'CH2_I_NPR',
    'CH2_I_NCR',
# //Okuma 3
    'CH3_I_M181',
    'CH3_I_M182',
    'CH3_I_M183',
    'CH3_I_M184',
    'CH3_I_AL',
    'CH3_I_PSA',
    'CH3_I_NPA',
    'CH3_I_NPR',
    'CH3_I_NCR',
# //Okuma 4
    'CH4_I_M181',
    'CH4_I_M182',
    'CH4_I_M183',
    'CH4_I_M184',
    'CH4_I_AL',
    'CH4_I_PSA',
    'CH4_I_NPA',
    'CH4_I_NPR',
    'CH4_I_NCR',
# //Robot
    'R_I_AL',
    'R_I_HF',
    'R_I_ID',
    'R_I_AUT_SEM',
    'R_O_AUT_SEM',
    'R_I_30_40',
    'R_I_CAS',
    'R_I_BIT0_CH',
    'R_I_BIT1_CH',
    'R_I_PAL',
    'R_I_DRW',
    'R_I_MA',
    'R_I_GET_PUT',
    'R_I_MA_CH',
    'R_I_G1_PS',
    'R_I_G2_PS',
    'R_I_FLS',
    'R_I_RLS',
# //Mesa 1
    'MA1_I_DR_U_PS_1',
    'MA1_I_DR_U_PS_2',
    'MA1_I_DR_D_PS_1',
    'MA1_I_DR_D_PS_2',
    'MA1_I_GS_UP',
    'MA1_I_GS_DN',
    'MA1_I_DR_U_ES_1',
    'MA1_I_DR_U_ES_2',
    'MA1_I_DR_D_ES_1',
    'MA1_I_DR_D_ES_2',
    'MA1_I_DR_U_NS',
    'MA1_I_DR_D_NS',
    'MA1_I_DR_U_BP_1_SA',
    'MA1_I_DR_U_BP_1_SR',
    'MA1_I_DR_U_BP_2_SA',
    'MA1_I_DR_U_BP_2_SR',
    'MA1_I_DR_D_BP_1_SA',
    'MA1_I_DR_D_BP_1_SR',
    'MA1_I_DR_D_BP_2_SA',
    'MA1_I_DR_D_BP_2_SR',
    'MA1_I_EMS',
    'MA1_I_SE_UP',
    'MA1_I_SE_DN',
# //Mesa 2
    'MA2_I_DR_U_PS_1',
    'MA2_I_DR_U_PS_2',
    'MA2_I_DR_D_PS_1',
    'MA2_I_DR_D_PS_2',
    'MA2_I_GS_UP',
    'MA2_I_GS_DN',
    'MA2_I_DR_U_ES_1',
    'MA2_I_DR_U_ES_2',
    'MA2_I_DR_D_ES_1',
    'MA2_I_DR_D_ES_2',
    'MA2_I_DR_U_NS',
    'MA2_I_DR_D_NS',
    'MA2_I_DR_U_BP_1_SA',
    'MA2_I_DR_U_BP_1_SR',
    'MA2_I_DR_U_BP_2_SA',
    'MA2_I_DR_U_BP_2_SR',
    'MA2_I_DR_D_BP_1_SA',
    'MA2_I_DR_D_BP_1_SR',
    'MA2_I_DR_D_BP_2_SA',
    'MA2_I_DR_D_BP_2_SR',
    'MA2_I_EMS',
    'MA2_I_SE_UP',
    'MA2_I_SE_DN',
# //Gral
    'Emergency',
    'Robot_IDLE',
# //Errores
    '.emergency_active',
    '.ma1_drd_endstops',
    '.ma1_dru_endstops',
    '.ma1_gs_dn',
    '.ma1_gs_up',
    '.ma1_nsense',
    '.ma2_drd_endstops',
    '.ma2_dru_endstops',
    '.ma2_gs_dn',
    '.ma2_gs_up',
    '.ma2_nsense',
    '.r_manualmode',
    '.r_program',
    '.r_gp1_not_free',
    '.r_gp2_not_free',
    '.r_gp1_free',
    '.r_gp2_free',
    '.r_not_idle',
    '.r_not_home',
    '.r_alarm',
    '.r_flimit',
    '.r_rlimit',
    '.ch1_nsense_ret',
    '.ch1_nsense_adv',
    '.ch1_alarm',
    '.ch1_psa',
    '.ch2_nsense_ret',
    '.ch2_nsense_adv',
    '.ch2_alarm',
    '.ch2_psa',
    '.ch3_nsense_ret',
    '.ch3_nsense_adv',
    '.ch3_alarm',
    '.ch3_psa',
    '.ch4_nsense_ret',
    '.ch4_nsense_adv',
    '.ch4_alarm',
    '.ch4_psa',
    '.init_error',
    '.max_unblock_error',
    '.max_block_error',
    '.max_pallet_present',
    '.max_dr_position',
    '.max_gs_up',
    '.chx_robot_not_allowed',
    '.chx_pressure_error',
    '.chx_nsense_adv',
    '.chx_nsense_ret',
    '.chx_alarm',
    '.chx_not_available',
# //Tags
    '.pause_auto',
    '.last_auto',
    '.pause_semi',
    '.CH1_DISABLE',
    '.CH2_DISABLE',
    '.CH3_DISABLE',
    '.CH4_DISABLE',
    '.MA1_DISABLE',
    '.MA2_DISABLE',
]

MSG_ERROR_DIRECTIONS = [

    '.emergency_active',
    '.ma1_drd_endstops',
    '.ma1_dru_endstops',
    '.ma1_gs_dn',
    '.ma1_gs_up',
    '.ma1_nsense',
    '.ma2_drd_endstops',
    '.ma2_dru_endstops',
    '.ma2_gs_dn',
    '.ma2_gs_up',
    '.ma2_nsense',
    '.r_manualmode',
    '.r_program',
    '.r_gp1_not_free',
    '.r_gp2_not_free',
    '.r_gp1_free',
    '.r_gp2_free',
    '.r_not_idle',
    '.r_not_home',
    '.r_alarm',
    '.r_flimit',
    '.r_rlimit',
    '.ch1_nsense_ret',
    '.ch1_nsense_adv',
    '.ch1_alarm',
    '.ch1_psa',
    '.ch2_nsense_ret',
    '.ch2_nsense_adv',
    '.ch2_alarm',
    '.ch2_psa',
    '.ch3_nsense_ret',
    '.ch3_nsense_adv',
    '.ch3_alarm',
    '.ch3_psa',
    '.ch4_nsense_ret',
    '.ch4_nsense_adv',
    '.ch4_alarm',
    '.ch4_psa',
    '.init_error',
    '.max_unblock_error',
    '.max_block_error',
    '.max_pallet_present',
    '.max_dr_position',
    '.max_gs_up',
    '.chx_robot_not_allowed',
    '.chx_pressure_error',
    '.chx_nsense_adv',
    '.chx_nsense_ret',
    '.chx_alarm',
    '.chx_not_available',

]

TAGS_DIRECTIONS = [
    '.step_auto',
    '.pause_auto',
    '.last_auto',
    '.pause_semi',
    '.step_semi',
]

# -------------------------------------------------------------------------------------------- #
# ----------------------------- ERROR MESSAGES LEYENDS --------------------------------------- #
# -------------------------------------------------------------------------------------------- #

MSG_ERROR_CODIFICATION = {

    '.emergency_active':'error emergencia activa',
    '.ma1_drd_endstops':'error diferencia en sensores endstops ma1 drawer abajo',
    '.ma1_dru_endstops':'error diferencia en sensores endstops ma1 drawer arriba',
    '.ma1_gs_dn':'error en el sensor de abajo de la persiana ma1',
    '.ma1_gs_up':'error en el sensor de arriba de la persiana ma1',
    '.ma1_nsense':'error sensor neumatico drawer del lado operario ma1',
    '.ma2_drd_endstops':'error diferencia en sensores endstops ma2 drawer abajo',
    '.ma2_dru_endstops':'error diferencia en sensores endstops ma2 drawer arriba',
    '.ma2_gs_dn':'error en el sensor de abajo de la persiana ma2',
    '.ma2_gs_up':'error en el sensor de arriba de la persiana ma2',
    '.ma2_nsense':'error sensor neumatico drawer del lado operario ma2',
    '.r_manualmode':'error robot en modo manual (fuerza reset de rutinas a paso 1)',
    '.r_program':'error robot diferencia entre programa (bits) kuka y plc',
    '.r_gp1_not_free':'error robot gripper 1 con pieza',
    '.r_gp2_not_free':'error robot gripper 2 con pieza',
    '.r_gp1_free':'error robot gripper 1 sin pieza',
    '.r_gp2_free':'error robot gripper 2 sin pieza',
    '.r_not_idle':'error robot sin idle',
    '.r_not_home':'error robot sin home flag',
    '.r_alarm':'error robot alarma de robot',
    '.r_flimit':'error robot forward limit sensor',
    '.r_rlimit':'error robot reverse limit sensor',
    
    '.ch1_nsense_ret':'error okuma 1 neumatica no retraida',
    '.ch1_nsense_adv':'error okuma 1 neumatica no avanzó',
    '.ch1_alarm':'error okuma 1 alarma',
    '.ch1_psa':'error okuma 1 sensor de presion',

    '.ch2_nsense_ret':'error okuma 2 neumatica no retraida',
    '.ch2_nsense_adv':'error okuma 2 neumatica no avanzó',
    '.ch2_alarm':'error okuma 2 alarma',
    '.ch2_psa':'error okuma 2 sensor de presion',

    '.ch3_nsense_ret':'error okuma 3 neumatica no retraida',
    '.ch3_nsense_adv':'error okuma 3 neumatica no avanzó',
    '.ch3_alarm':'error okuma 3 alarma',
    '.ch3_psa':'error okuma 3 sensor de presion',

    '.ch4_nsense_ret':'error okuma 4 neumatica no retraida',
    '.ch4_nsense_adv':'error okuma 4 neumatica no avanzó',
    '.ch4_alarm':'error okuma 4 alarma',
    '.ch4_psa':'error okuma 4 sensor de presion',

    '.init_error':'error en check inicial',
    '.max_unblock_error':'error desbloqueo pallet y mesa seleccionados',
    '.max_block_error':'error bloqueo pallet y mesa seleccionados',
    '.max_pallet_present':'error hay un pallet en la posición',
    '.max_dr_position': 'error posicion drawer seleccionado no esta del lado del robot',
    '.max_gs_up': 'error en el sensor de arriba de la persiana mesa seleccionada',
    '.chx_robot_not_allowed': 'error de ingreso robot',
    '.chx_pressure_error':'error presion neumatica para el okuma seleccionado',
    '.chx_nsense_adv':'error sensor avance neumatico para el okuma seleccionado',
    '.chx_nsense_ret':'error sensor retroceso neumatico para el okuma seleccionado',
    '.chx_alarm': 'error alarma para el okuma seleccionado',
    '.chx_not_available':'error okuma seleccionado no disponible ',
}


# -------------------------------------------------------------------------------------------- #
# ---------------------------------- Routines Parameters ------------------------------------- #
# -------------------------------------------------------------------------------------------- #


OKUMA = {
    'okuma_1' : 1,
    'okuma_2' : 2,
    'okuma_3' : 3,
    'okuma_4' : 4,
    'okuma_current_selected': 0,
}

MESA = {
    'mesa_1' : 1,
    'mesa_2' : 2,
    'mesa_current_selected': 0,
}
