# Generated by Django 3.2.8 on 2022-07-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('log', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
