# Generated by Django 3.2 on 2022-08-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='description',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='unit',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parameter',
            name='value',
            field=models.DecimalField(decimal_places=3, default=2, max_digits=10, max_length=20),
            preserve_default=False,
        ),
    ]
